name: Tests

on:
  push:
    branches:
      - master
    tags:
      - 'v[0-9]+\.*'
  pull_request:
    branches:
      - master
      - develop
      - 'v[0-9]+.[0-9]+'

env:
  CARGO_TERM_COLOR: always

jobs:
  testing:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-13, macos-latest, windows-latest ]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Test ${{matrix.os}}
        run: cargo test --workspace --all-features --no-fail-fast
